<?php

namespace covoiturage\covoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * etapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etapeRepository extends EntityRepository
{
}
