<?php

namespace covoiturage\covoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * preferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preferenceRepository extends EntityRepository
{
}
