<?php

namespace covoiturage\covoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * reservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends EntityRepository
{
    
     public function getReservSend($userID){
        $qd = $this->createQueryBuilder('a')
                ->select('a')
                ->where('a.utilisateur_send_id = :userID')
                ->orderBy('a.');
     }
}
