<?php

namespace covoiturage\covoiturageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * reservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reservationRepository extends EntityRepository
{
}
