Utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix: /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile